### ISSUE TITLE
Version deployment bug

### ISSUE THREAD

**Issue by bagjohn** [bagjohn/larvaworld_autoversioning#8]
Since a recent successful commit all others fail during the version deployment action. By using print statements the bug has been traced to occur when the default dataset is analyzed for the first time during the registry initialization.

More specifically at the annotation step when the chunk_dicts is created via its setter, or maybe during its storage. At that moment a dictionary (chunk_dicts) is turned to a pd.DataFrame in order to be stored at the data.h5 file, the main hdf5 file of the Larvaworld dataset format. Nothing has been changed in that part of the code lately. 

The location is lib.process.dataset.py. 

A test must be created to figure out what exactly fails. 

Please see failed actions for more info.

**Comment by bagjohn** [comment]
Possibly has to do with the pytables dependency. Though when I tried to add it to the pyproject.toml it failed to collect it because it needs python>=3.9

**Comment by bagjohn** [comment]
Adding the tables dependency resolves the previous issue. Now there is another bug possibly related to the pysimplegui pkg.

The error:
_tkinter.TclError: no display name and no $DISPLAY environment variable

**Comment by almoehi** [comment]
It works locally because you have a display. The GitHub runners are headless and do not have a display. Either one need to install framebuffer (which will provide a display) or refactor code such that it does not open pysimpleGUI.

It seems the build issues to have started when merging my original PR. Which did not have changes related to this.

What I assume is that some package got upgraded and that triggered a cascade of other package updates.

Maybe more set restrictive version pinning to prevent unwanted automatic updates. For example pin the major.minor versions.

**Comment by almoehi** [comment]
Check solution 2 from here how get a display:

https://arbitrary-but-fixed.net/2022/01/21/headless-gui-github-actions.html

**Comment by bagjohn** [comment]
Bug temporarily solved by pinning PySimpleGUI dependency to version 4

**Comment by bagjohn** [comment]
Now a new bug comes up :
/opt/hostedtoolcache/Python/3.8.18/x64/bin/python: No module named larvaworld.__main__; 'larvaworld' is a package and cannot be directly executed

The registry configuration completes succesfully. Any idea where this error emerges?

**Comment by bagjohn** [comment]
The error is probably raised by the following line in larvaworld_autoversioning.yml that defines the github actions :
`python -m larvaworld`
since larvaworld is a package and not a module

**Comment by bagjohn** [comment]
Removing this line allowed the versioning to run normally
